version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT:-8000}:8000" # Default to 8000 if PORT is not set
    environment:
      - BRANCH_NAME=${BRANCH_NAME:-default}
