name: Deploy Uvicorn App with Docker

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Transfer Files to Server
        env:
          SERVER_IP: 98.66.233.254
          SERVER_USER: paul_virtuology
          SERVER_PASSWORD: Andriamatoa301
        run: |
          sshpass -p "${SERVER_PASSWORD}" rsync -avz \
          -e "ssh -o StrictHostKeyChecking=no" \
          ./ ${SERVER_USER}@${SERVER_IP}:~/uvicorn-app

      - name: Deploy with Docker
        env:
          SERVER_IP: 98.66.233.254
          SERVER_USER: paul_virtuology
          SERVER_PASSWORD: Andriamatoa301
        run: |
          sshpass -p "${SERVER_PASSWORD}" ssh -o StrictHostKeyChecking=no ${SERVER_USER}@${SERVER_IP} "
          cd ~/uvicorn-app &&
          echo \"PORT=8001\nBRANCH_NAME=main\" > .env &&
          sudo docker-compose down &&
          sudo docker-compose up -d
          "
