name: Deploy Uvicorn App with Docker

on:
  push:
    branches:
      - main
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Transfer Files to Server
        env:
          SERVER_IP: 98.66.233.254
          SERVER_USER: paul_virtuology
          SERVER_PASSWORD: Andriamatoa301
        run: |
          sshpass -p "${SERVER_PASSWORD}" rsync -avz \
          -e "ssh -o StrictHostKeyChecking=no" \
          ./ ${SERVER_USER}@${SERVER_IP}:~/uvicorn-branch-app

      - name: Deploy with Docker
        env:
          SERVER_IP: 98.66.233.254
          SERVER_USER: paul_virtuology
          SERVER_PASSWORD: Andriamatoa301
          BRANCH_NAME: ${{ github.ref_name }}
        run: |
          sshpass -p "${SERVER_PASSWORD}" ssh -o StrictHostKeyChecking=no ${SERVER_USER}@${SERVER_IP} "
          cd ~/uvicorn-branch-app &&
          export PORT=\$( [ '${{ github.ref_name }}' = 'main' ] && echo '8001' || echo '8002' ) &&
          echo Using PORT=\$PORT and BRANCH_NAME=${{ github.ref_name }} &&
          echo \"PORT=\$PORT\nBRANCH_NAME=${{ github.ref_name }}\" > .env &&
          sudo docker-compose down &&
          sudo docker-compose up -d
          "
