name: Deploy Uvicorn App

on:
  push:
    branches:
      - main
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Transfer Files to Server
        env:
          SERVER_IP: 98.66.233.254
          SERVER_USER: paul_virtuology
          SERVER_PASSWORD: Andriamatoa301
        run: |
          sshpass -p "${SERVER_PASSWORD}" rsync -avz \
          --exclude '.git' \
          --exclude '.github' \
          ./ ${SERVER_USER}@${SERVER_IP}:~/uvicorn-branch-app

      - name: Install Dependencies on Server
        env:
          SERVER_IP: 98.66.233.254
          SERVER_USER: paul_virtuology
          SERVER_PASSWORD: Andriamatoa301
        run: |
          sshpass -p "${SERVER_PASSWORD}" ssh -o StrictHostKeyChecking=no ${SERVER_USER}@${SERVER_IP} "
          cd ~/uvicorn-branch-app &&
          pip install -r requirements.txt
          "

      - name: Restart Uvicorn App
        env:
          SERVER_IP: 98.66.233.254
          SERVER_USER: paul_virtuology
          SERVER_PASSWORD: Andriamatoa301
        run: |
          BRANCH_NAME=${{ github.ref_name }}
          sshpass -p "${SERVER_PASSWORD}" ssh -o StrictHostKeyChecking=no ${SERVER_USER}@${SERVER_IP} "
          cd ~/uvicorn-branch-app &&
          ./start_app.sh $BRANCH_NAME
          "
